name: Publish Experimental Packages

on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write
  contents: read

jobs:
  publish-experimental:
    strategy:
      matrix:
        package:
          - blade
    uses: ronin-co/actions/.github/workflows/publish-experimental.yml@main
    with:
      package_dir: './packages/${{ matrix.package }}'
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN_READ_AND_WRITE }}
