name: Update

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    if: github.actor == 'dependabot[bot]'
    uses: ronin-co/actions/.github/workflows/update-dependabot-pr.yml@main
    secrets: inherit
